[package]
name = "covcon"
version = "0.1.0"
edition = "2021"

[dependencies]
insta = { version = "1.41.1", features = ["ron"] }
quick-xml = { version = "0.37.1", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
